name: Setup CodeCov
on: [push, pull_request]
jobs:
  codecov:
    name: Setup code coverage report
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo C:\Program Files\OpenCppCoverage >> %PATH%

      - name: Build and Run Unit Tests
        run: |
          # Change to the project directory
          cd Eventures

          # Run qmake and build commands
          cmd /c src\qmake Eventures.pro
          make
          ./UnitTests


      - name: Generate Coverage Report
        id: generate_test_report
        run: OpenCppCoverage.exe --sources src --export_type cobertura:coverage.xml -- ./UnitTests

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
